# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_jadwal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1079, 922)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(250, 0))
        self.frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame.setStyleSheet("background-color: rgb(44, 62, 80);\n"
"border-radius: 12px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Poppins Black")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_6)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins Black")
        self.pushButton.setFont(font)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(52, 73, 94);\n"
"text-align: left;\n"
"padding-left: 10px;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3498DB;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_2.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins Black")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(52, 73, 94);\n"
"text-align: left;\n"
"padding-left: 10px;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3498DB;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_11.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins Black")
        self.pushButton_11.setFont(font)
        self.pushButton_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(52, 73, 94);\n"
"text-align: left;\n"
"padding-left: 10px;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3498DB;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_3.addWidget(self.pushButton_11)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_3.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins Black")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(52, 73, 94);\n"
"text-align: left;\n"
"padding-left: 10px;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3498DB;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins Black")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(52, 73, 94);\n"
"text-align: left;\n"
"padding-left: 10px;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3498DB;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_10.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins Black")
        self.pushButton_10.setFont(font)
        self.pushButton_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(52, 73, 94);\n"
"text-align: left;\n"
"padding-left: 10px;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3498DB;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_5.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins Black")
        self.pushButton_5.setFont(font)
        self.pushButton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(52, 73, 94);\n"
"text-align: left;\n"
"padding-left: 10px;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3498DB;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_9.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins Black")
        self.pushButton_9.setFont(font)
        self.pushButton_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(52, 73, 94);\n"
"text-align: left;\n"
"padding-left: 10px;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3498DB;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_3.addWidget(self.pushButton_9)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setMinimumSize(QtCore.QSize(800, 900))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Poppins Black")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_4)
        self.tableWidget.setGeometry(QtCore.QRect(20, 340, 752, 391))
        self.tableWidget.setStyleSheet("border: 1px solid #333;\n"
"border-radius: 0px;\n"
"")
        self.tableWidget.setRowCount(3)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(30, 35, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(30, 74, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(30, 112, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(30, 200, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_6.setGeometry(QtCore.QRect(170, 240, 101, 28))
        self.pushButton_6.setAccessibleDescription("")
        self.pushButton_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 0);\n"
"text-align: center;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(170, 255, 127);    \n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setGeometry(QtCore.QRect(280, 240, 93, 28))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(52, 73, 94);\n"
"text-align: center;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3498DB;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_8.setGeometry(QtCore.QRect(380, 240, 93, 28))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);\n"
"text-align: center;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(255, 0, 0);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.frame_4)
        self.dateTimeEdit.setGeometry(QtCore.QRect(160, 30, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_2.setGeometry(QtCore.QRect(160, 69, 521, 22))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("border: 1px solid #336699;\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_3.setGeometry(QtCore.QRect(161, 108, 521, 22))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("border: 1px solid #336699;\n"
"")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_4.setGeometry(QtCore.QRect(162, 196, 521, 22))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("border: 1px solid #336699;\n"
"")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(28, 154, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.comboBox_5 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_5.setGeometry(QtCore.QRect(160, 150, 521, 22))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        self.comboBox_5.setFont(font)
        self.comboBox_5.setStyleSheet("border: 1px solid #336699;\n"
"")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_7.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.tableWidget.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.dateTimeEdit.raise_()
        self.comboBox_2.raise_()
        self.comboBox_3.raise_()
        self.comboBox_4.raise_()
        self.label_9.raise_()
        self.comboBox_5.raise_()
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "SI PHOTO STUDIO"))
        self.pushButton.setText(_translate("Form", "Dashboard"))
        self.pushButton_2.setText(_translate("Form", "User"))
        self.pushButton_11.setText(_translate("Form", "Fotografer"))
        self.pushButton_3.setText(_translate("Form", "Produk"))
        self.pushButton_4.setText(_translate("Form", "Customer"))
        self.pushButton_10.setText(_translate("Form", "Pembelian"))
        self.pushButton_5.setText(_translate("Form", "Penjualan"))
        self.pushButton_9.setText(_translate("Form", "Jadwal Foto"))
        self.label.setText(_translate("Form", "🧑‍💼 JADWAL FOTO"))
        self.frame_4.setStyleSheet(_translate("Form", "QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(52, 73, 94);\n"
"text-align: center;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3498DB;\n"
"}"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "John Doe"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "Jane Smith"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Form", "Bob Johnson"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("Form", "Tanggal :"))
        self.label_4.setText(_translate("Form", "Fotografer : "))
        self.label_5.setText(_translate("Form", "Status :"))
        self.label_7.setText(_translate("Form", "Customer :"))
        self.pushButton_6.setText(_translate("Form", "Tambah"))
        self.pushButton_7.setText(_translate("Form", "Edit"))
        self.pushButton_8.setText(_translate("Form", "Hapus"))
        self.comboBox_2.setItemText(0, _translate("Form", "3"))
        self.comboBox_2.setItemText(1, _translate("Form", "6"))
        self.comboBox_2.setItemText(2, _translate("Form", "7"))
        self.comboBox_3.setItemText(0, _translate("Form", "Proses"))
        self.comboBox_3.setItemText(1, _translate("Form", "Selesai"))
        self.comboBox_4.setItemText(0, _translate("Form", "1"))
        self.comboBox_4.setItemText(1, _translate("Form", "2"))
        self.comboBox_4.setItemText(2, _translate("Form", "3"))
        self.comboBox_4.setItemText(3, _translate("Form", "4"))
        self.comboBox_4.setItemText(4, _translate("Form", "5"))
        self.label_9.setText(_translate("Form", "Jenis Sesi :"))
        self.comboBox_5.setItemText(0, _translate("Form", "Pernikahan"))
        self.comboBox_5.setItemText(1, _translate("Form", "Wisuda"))
        self.comboBox_5.setItemText(2, _translate("Form", "Keluarga"))
        self.comboBox_5.setItemText(3, _translate("Form", "Event"))
        self.comboBox_5.setItemText(4, _translate("Form", "Produk"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
